{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "ultrabuilder",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gettoackebf2hj43qcwcl2d5ga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ultrabuilder-1.1.1.jar",
          "url": "ultrabuilder-1.1.1.jar",
          "size": 15412,
          "sha512": "f2c26cc18d2806672334f36640146058ed46f5b51c22f4aba75b10e4b49c2a28c5ee999bb2d0bab2da58550383f53baa4a631dc2d394654b681f189fe542a692",
          "sha256": "fc8bf5be1b8e3536fe535fb33282828707c1254c65e5524ad154a4989c780153",
          "sha1": "45d19f12d1e708d185c27d88ae15afe33b725a1a",
          "md5": "7bc1811f5bd61cfb48da2aa35d8cde99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.60"
          }
        }
      ],
      "files": [
        {
          "name": "ultrabuilder-1.1.1.jar",
          "url": "ultrabuilder-1.1.1.jar",
          "size": 15412,
          "sha512": "f2c26cc18d2806672334f36640146058ed46f5b51c22f4aba75b10e4b49c2a28c5ee999bb2d0bab2da58550383f53baa4a631dc2d394654b681f189fe542a692",
          "sha256": "fc8bf5be1b8e3536fe535fb33282828707c1254c65e5524ad154a4989c780153",
          "sha1": "45d19f12d1e708d185c27d88ae15afe33b725a1a",
          "md5": "7bc1811f5bd61cfb48da2aa35d8cde99"
        }
      ]
    }
  ]
}
