{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "ultrabuilder",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "qhy6zj3wfrdixilydlulo5rmz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ultrabuilder-1.1.2.jar",
          "url": "ultrabuilder-1.1.2.jar",
          "size": 14618,
          "sha512": "c59d842eb124ca353ee807e52a398d17ff33b40d96ecc495c9abe890f56b93e7f0bea478621477ff8b70426a98c7eaef5b0c25bbfbcebb287d15b86c5dd917da",
          "sha256": "bfe42ddb06c521b9954da15d3493f1d505c0865b7f4622ca241b3b209c524fd3",
          "sha1": "0a564d09c96709348430b396fca2e74f00ee9041",
          "md5": "3751ba2f699e3c74fad0fcf6b8f4e3f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.60"
          }
        }
      ],
      "files": [
        {
          "name": "ultrabuilder-1.1.2.jar",
          "url": "ultrabuilder-1.1.2.jar",
          "size": 14618,
          "sha512": "c59d842eb124ca353ee807e52a398d17ff33b40d96ecc495c9abe890f56b93e7f0bea478621477ff8b70426a98c7eaef5b0c25bbfbcebb287d15b86c5dd917da",
          "sha256": "bfe42ddb06c521b9954da15d3493f1d505c0865b7f4622ca241b3b209c524fd3",
          "sha1": "0a564d09c96709348430b396fca2e74f00ee9041",
          "md5": "3751ba2f699e3c74fad0fcf6b8f4e3f9"
        }
      ]
    }
  ]
}
