{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "githooker",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6x5gpoq6izaz5gsvalvzr3cb44"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "githooker-1.0.3.jar",
          "url": "githooker-1.0.3.jar",
          "size": 66134,
          "sha512": "8123edad58ba984475ee656810170e477c44c3b62e966c90bc44d0eb0a111635022a6d571b8ab48e110fdab1307679d52f7920b97527d0d85c6e6a3a78681571",
          "sha256": "b2c0b19ebeb928f081787d40c4c77da852530a05ceb434084ed56e8d3dcdf0e0",
          "sha1": "c6fd3bee41fc95c9f6d9cc6f6c62be32616ecdd3",
          "md5": "eacc2c2389e9fc95394c78b57845acce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.60"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "githooker-1.0.3.jar",
          "url": "githooker-1.0.3.jar",
          "size": 66134,
          "sha512": "8123edad58ba984475ee656810170e477c44c3b62e966c90bc44d0eb0a111635022a6d571b8ab48e110fdab1307679d52f7920b97527d0d85c6e6a3a78681571",
          "sha256": "b2c0b19ebeb928f081787d40c4c77da852530a05ceb434084ed56e8d3dcdf0e0",
          "sha1": "c6fd3bee41fc95c9f6d9cc6f6c62be32616ecdd3",
          "md5": "eacc2c2389e9fc95394c78b57845acce"
        }
      ]
    }
  ]
}
