{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "githooker",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4kqluxwf4jg2ppagolgpfzu7wq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "githooker-1.0.2.jar",
          "url": "githooker-1.0.2.jar",
          "size": 66134,
          "sha512": "a22f34f9c42524b3210513de4c098b7c91bdb1cd446bda11d6b4ac2a5e238b284a7607585f7ae767946c23cbdd7b9d0b949921b0e88e32bb30f22da85c363339",
          "sha256": "d409562d4e3cc152c9b1e691234cb1129e60ee0af53719f647507cdee4194eeb",
          "sha1": "a912f033d7cd1299d67f905aa4a1fd27bfe43279",
          "md5": "e6c04375f6871e7cb713aa4623691015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.60"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "githooker-1.0.2.jar",
          "url": "githooker-1.0.2.jar",
          "size": 66134,
          "sha512": "a22f34f9c42524b3210513de4c098b7c91bdb1cd446bda11d6b4ac2a5e238b284a7607585f7ae767946c23cbdd7b9d0b949921b0e88e32bb30f22da85c363339",
          "sha256": "d409562d4e3cc152c9b1e691234cb1129e60ee0af53719f647507cdee4194eeb",
          "sha1": "a912f033d7cd1299d67f905aa4a1fd27bfe43279",
          "md5": "e6c04375f6871e7cb713aa4623691015"
        }
      ]
    }
  ]
}
