{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "githooker",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nh2ya7j7gvabjcjgggtr7g2kwq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "githooker-1.0.1.jar",
          "url": "githooker-1.0.1.jar",
          "size": 66135,
          "sha512": "413bb37be692c9f5dea19d7308a31e6c0ebdcd608c9c5ac4ac4a4ba0bdb4d57f26a685b4651d0946c5513ca61fd3dddb8015a33390e78434e990550847d0dcbc",
          "sha256": "9ceced9bef083310bb0b87594b430eac43d390a94b00624c9eb0d2baa86ae987",
          "sha1": "51521bce419274c40ddab6f378afa7be20a00365",
          "md5": "64b631b0746ac455e34b54575ea3c6ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "githooker-1.0.1.jar",
          "url": "githooker-1.0.1.jar",
          "size": 66135,
          "sha512": "413bb37be692c9f5dea19d7308a31e6c0ebdcd608c9c5ac4ac4a4ba0bdb4d57f26a685b4651d0946c5513ca61fd3dddb8015a33390e78434e990550847d0dcbc",
          "sha256": "9ceced9bef083310bb0b87594b430eac43d390a94b00624c9eb0d2baa86ae987",
          "sha1": "51521bce419274c40ddab6f378afa7be20a00365",
          "md5": "64b631b0746ac455e34b54575ea3c6ae"
        }
      ]
    }
  ]
}
