{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pmachovec",
    "module": "ultrabuilder",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "y4jpsdmbnrgm5aykojefe5fgky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ultrabuilder-1.1.jar",
          "url": "ultrabuilder-1.1.jar",
          "size": 15412,
          "sha512": "292772b9a5471f5f67455bea9b99d5a502e033df7cc4b10ce897194d857e3b8a73995b871527bc50f308bf35ec7fd60da09b2971d3f8e51b37f4f670acecca9a",
          "sha256": "350170a208861f2f8925d70243bf57929445ebdddf67b8a551a2bf9cc1fa3a02",
          "sha1": "657f94002708d58da297ceca3339b16969eab1e6",
          "md5": "f27479d1ebeed8dcdf1b6a9bb404e903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.60"
          }
        }
      ],
      "files": [
        {
          "name": "ultrabuilder-1.1.jar",
          "url": "ultrabuilder-1.1.jar",
          "size": 15412,
          "sha512": "292772b9a5471f5f67455bea9b99d5a502e033df7cc4b10ce897194d857e3b8a73995b871527bc50f308bf35ec7fd60da09b2971d3f8e51b37f4f670acecca9a",
          "sha256": "350170a208861f2f8925d70243bf57929445ebdddf67b8a551a2bf9cc1fa3a02",
          "sha1": "657f94002708d58da297ceca3339b16969eab1e6",
          "md5": "f27479d1ebeed8dcdf1b6a9bb404e903"
        }
      ]
    }
  ]
}
